### PR TITLE
Backup status monitor

### LINKED ISSUE #6: Create backup monitor
Create a system for easily monitoring what has already been backed up, what needs to be backed up, what backups are stale, etc.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #6.

The backup status is visible at https://portal.nersc.gov/project/desi/collab/backups/.  Please use this PR for additional comments on that page and the infrastructure behind it.

For consideration:

1. Decide what to do with the external directory.  Unless we have a specific future use case in mind for it, it would be more appropriate to list it under the 'Other Backups' section.
2. I propose setting the status of the metadata directory to 'no backups'.  I don't think anyone will be too upset if we lose data in that directory, since it is regenerated every night.  That said, we have not deleted anything from that directory, although older data gets compressed on a regular basis.

### CODE REVIEW

**Comment by weaverba137** [comment]
PS:

3. We should decide on a cadence for updating the backup status.

**Comment by sbailey** [comment]
Overall looks nice.  There is a disconcerting amount of non-green, but it is the purpose of the backup monitor to alert us to those situations so that we can get more backed up.

The "potential backups" JSON entries were empty dictionaries for every case I checked.

Are the CSV files sorted by anything, e.g. timestamp?  If they aren't sorted, sorting by name might be convenient for a human scanning them.

Please add backupStatus.sh docs to https://desi.lbl.gov/trac/wiki/Pipeline/Backups#UpdatingdesiBackupConfiguration, in particular
* link to the status page
* who/what runs it and how often
* where to update the comments
* how to add a directory to the "NO BACKUP" list

If desi.json is setup to backup blat/foo/ while excluding blat/foo/bar and the backup has successfully run, does that put blat/ into the "complete" state or "in progress" state?

OK to not backup the metadata directory to HPSS, but we should copy the latest inventory to NOAO or elsewhere at a regular cadence.  If /project had a major failure, it would be really helpful to have an inventory of what we lost to know what we are trying to recreate.  And we can't rely upon /project to host the file of what we would lose if we lost /project :)

Backup + monitor check cadence: let's try weekly.

OK to move external/ into other backups, but let's keep the directory even if it only has a README for now.

**Comment by weaverba137** [comment]
Moving discussion from email into PR:

> At the very high level that this is being reported at, almost no directories would ever be "complete" under that definition except for protodesi.
>
> Basic operational question: I know that the /project backups are not intended to be incremental, but it looks like from the desi.json config file it does support the idea of pattern matching generating new backups, e.g. 
> ```
>       "buzzard":{
>            "buzzard/README.html":"buzzard/README.html",
>            "buzzard/buzzard_v([0-9.]+)_desicut/([0-9])/([0-9])/.*$":"buzzard/buzzard_v\\1_desicut/\\2/buzzard_v\\1_desicut_\\2_\\3.tar",
>            "buzzard/buzzard_v([0-9.]+)_desicut/lensed/([0-9])/([0-9])/.*$":"buzzard/buzzard_v\\1_desicut/lensed/\\2/buzzard_v\\1_desicut_lensed_\\2_\\3.tar"
>        },
> ```
> Does that mean if a new buzzard mock shows up, it would automatically get backed up on the next run of desiBackup.sh, without anyone needing to update the desi.json config file?
>
> i.e. if we run desiBackup.sh to completion before running the backup monitor script, I don't think we'd be in a situation of "It's automated and if we're off by a day or so, that's just down to the timing of the backups" because the backup has already done the best it can without human intervention before the checker ran.  The only gotcha would be for new data showing up between the time of the backup and the check running immediately afterward.

That is essentially correct.  The trick is getting a configuration for the data, which means that the owners of the data have to know what they're doing well enough for that configuration to be stable.

> Agreed that daily is too frequently.  Does it use the scans that NERSC generates for us, or does it have to traverse the filesystem itself?  If it isn't too intrusive, running weekly would.  Monthly would be ok, but preferably not longer than that.

It scans the filesystem, but it doesn't take very long. I ran through several full tests yesterday.  I think weekly will be just fine.  Aside: historically, I have found those NERSC scans very difficult to work with.  The files are huge and they are not in any obvious order.  In other words, to find the contents of one directory, you have to scan the entire file.

**Comment by weaverba137** [comment]
> The "potential backups" JSON entries were empty dictionaries for every case I checked.

Right.  That means that everything that is *configured* for backup is already backed up.  The log files will show directories that are not configured yet.

> Are the CSV files sorted by anything, e.g. timestamp? If they aren't sorted, sorting by name might be convenient for a human scanning them.

I don't think those have any deliberate sorting, but applying that sort would require some changes to the hpsspy library.  Sorting would require having all the files in memory, which is potentially a problem for lots of files.  Instead, the idea is to scan the filesystem as fast as possible and immediately write the files to a cache file so they *don't* have to live in memory.

> Please add backupStatus.sh docs to...

Will do.

> If desi.json is setup to backup blat/foo/ while excluding blat/foo/bar and the backup has successfully run, does that put blat/ into the "complete" state or "in progress" state?

I believe that would be detected as "in progress", but I will double-check.

> OK to not backup the metadata directory to HPSS, but we should copy the latest inventory...

That's fine, but I have to check to see what space we have set up for DESI at NERSC.

> OK to move external/ into other backups...

Will do.

**Comment by weaverba137** [comment]
Follow up:

> If desi.json is setup to backup blat/foo/ while excluding blat/foo/bar and the backup has successfully run, does that put blat/ into the "complete" state or "in progress" state?

Yes, that would put it "in progress".

**Comment by weaverba137** [comment]
I have updated https://desi.lbl.gov/trac/wiki/Pipeline/Backups, please review that.

**Comment by weaverba137** [comment]
@sbailey: is this ready to be merged and checked off in P6?  I don't think regular `lya_forest` backups are going to happen any time soon, and that shouldn't hold this up in any case.

**Comment by sbailey** [comment]
From wiki page documentation: "Certain directories are excluded from backups. This is also set in backupStatus.sh: ..."  That appears to apply to top level directories being excluded from backups, but not specific subdirectories of directories that are otherwise backed up, which are covered by the desi.json config file instead.

e.g. "spectro" is flagged as "in progress" with the hardcoded comment "only partially configured for backup".  But I don't see how to easily identify whether everything that is supposed to be backed up in there is backed up, or which of the non-backed up portions are specifically and purposefully excluded vs. haven't been added to the configuration yet (thus requiring human attention).

From an earlier comment and answer:

>> If desi.json is setup to backup blat/foo/ while excluding blat/foo/bar and the backup has successfully run, does that put blat/ into the "complete" state or "in progress" state?

> Yes, that would put it "in progress".

We need to somehow distinguish between
  * in progress because stuff that is supposed to be backed up isn't actually backed up yet for some reason
  * everything that is supposed to be backed up is backed up, and everything that remains is specifically and purposefully excluded from backup
  * everything in this subdirectory that is configured for back up has been backed up, but it contains new files/directories that aren't covered by either the exclude or backup list, and thus require attention (which seems different from the current "no configuration" top level state)

Returning to the high level goals — the automated backup monitor should help us identify:
* is everything that is supposed to be backed up actually backed up?
* have any new directories or files appeared that are not covered by the backup configuration and need human attention?  This should include any subdirectories of things that previously were configured and completely backed up, but now contain new things that aren't backed up.
  * related: what are those things?  e.g. is any of mocks/lya_forest backed up now?  none of it?  I want to distinguish between humans mentally parsing the configuration file for what they think it is supposed to be doing, vs. an automated checker verifying what is on disk vs. what is supposed to be on HPSS vs. what is actually on HPSS vs. what is falling through the gaps.
* has anything been hanging out in the "we intend to back this up eventually but it isn't quite ready..." state for too long?  e.g. mocks/lya_forest.  This is different from the permanent exclusions, e.g. for the metadata directory that we know we don't intended to backup, and we don't want to be distracted every month revisiting that question.

This PR is progress in these directions, but I don't feel like it actually addresses the need in a way that we can just close this out as "done; we have an automated backup system that meets our needs".  Could you clarify whether it does do those things above and I'm just misunderstanding, or otherwise expand the functionality?  Thanks.

**Comment by sbailey** [comment]
P.S. I agree that the backup status of `mocks/lya_forest` itself shouldn't be a blocking factor for merging this or checking it off in P6, but I think we are still iterating on the features and usability of what we want the automated backup monitor tool to do.  Feel free to suggest items for "please go ahead and merge this PR but I'll open tickets to address X and Y separately so that this doesn't become a mega-PR".  i.e. we could go ahead and merge this, while still requesting additional functionality via other PRs before closing in P6.

**Comment by weaverba137** [comment]
> From wiki page documentation: "Certain directories are excluded from backups. This is also set in backupStatus.sh: ..." That appears to apply to top level directories being excluded from backups, but not specific subdirectories of directories that are otherwise backed up, which are covered by the desi.json config file instead.
> 
> e.g. "spectro" is flagged as "in progress" with the hardcoded comment "only partially configured for backup". But I don't see how to easily identify whether everything that is supposed to be backed up in there is backed up, or which of the non-backed up portions are specifically and purposefully excluded vs. haven't been added to the configuration yet (thus requiring human attention).

Maybe I didn't explain the function of the various log files adequately.

1. If a directory tree is configured AND backed up: this is indicated by the *absence* of warnings about missing backups in the log files, and the *presence* of matching (mostly htar) files in the files on HPSS logs.
2. If a directory tree is configured BUT NOT backed up: there will be warnings about files missing from HPSS in the log files.  *As it happens, there are zero directories in this state.*
3. If a directory tree is NOT configured: there will be warnings about about the non-configured directories in the log files.

> We need to somehow distinguish between
> 
> * in progress because stuff that is supposed to be backed up isn't actually backed up yet for some reason

That is indicated by item 2 above.

> * everything that is supposed to be backed up is backed up, and everything that remains is specifically and purposefully excluded from backup

That should be indicated by item 1 above.

>  *   everything in this subdirectory that is configured for back up has been backed up, but it contains new files/directories that aren't covered by either the exclude or backup list, and thus require attention (which seems different from the current "no configuration" top level state)

That should be indicated by item 3 above.

> Returning to the high level goals — the automated backup monitor should help us identify:

I actually don't see how what I have done fails to meet those goals, although I admit my documentation of the log files could be improved.

Please remember that I can do the best we can, but there are clearly cases where even the experts writing the data have no clue what is supposed to be backed up or not.  Short of forcing people to use $SCRATCH or desi/users for all intermediate data, there will always be things in an intermediate state.  The automation I've written finds those things.

**Comment by weaverba137** [comment]
Let me offer another viewpoint on this.  This is an automated backup system that can handle arbitrarily-structured, petabyte-scale datasets.  I think that's an achievement in and of itself.  This system, if we are completely honest with ourselves, will only ever be used by trained experts, *and this is a good thing*.  I think that satisfies managerial requirements.  Everything else is micromanaging presentation details.  At least that's how I'm seeing it.

**Comment by sbailey** [comment]
After analog discussion with Ben, we'll merge this PR now and I'll document further feature/functionality requests in separate tickets for future PRs.

**Pull request merged**
